# A. In the penguins dataset, transform a numeric variable to a categorical one
# by aggregating values into classes. Consider the flipper length variable and 
# create 10mm wide classes using the cut() funtcion (hint: use the range() funtcion
# to determine the min and max values of the variable, then define a sequence for the
# cuts).
library(palmerpenguins)
library(ggplot2)

data("penguins")

flipper <- penguins$flipper_length_mm[!is.na(penguins$flipper_length_mm)]
range(flipper)

# create 10mm wide classes
classes <- seq(170, 240, 10) 

flipper_cut <- cut(flipper, breaks = classes,
                   include.lowest = TRUE, right = FALSE)

head(flipper_cut)

# B. Use the table() function on the new variable generated by cut(). Then 
# transform it into a data.frame object. Rename the columns accordingly using
# the colnamse() function (hint: the second column correspond to the absolute 
# frequencies).
flipper_df <- data.frame(table(flipper_cut))
colnames(flipper_df) <- c("flipper_length_mm", "absolute_freq")

# C. Add the columns for: relative frequencies, cumulative absolute frequencies 
# and cumulative relative frequencies.
flipper_df$relative_freq <- flipper_df$absolute_freq / sum(flipper_df$absolute_freq)
flipper_df$cumulative_absolute_freq <- cumsum(flipper_df$absolute_freq)
flipper_df$cumulative_relative_freq <- cumsum(flipper_df$relative_freq) 

# D. Use the geom_col() function to plot the frequency of each class. Then, using
# the geom_text(aes(label = ...)) function, add the relative frequency as a percentage
# above each column (hint: substitute the ... with the relative frequency values. Use
# the round() function to choose the appropriate number of digits).

# png("./plots/flipper_lengths_distribution")
ggplot(flipper_df, aes(x = flipper_length_mm, y = absolute_freq)) +
  geom_col() +
  geom_text(aes(label = paste0(
    round(relative_freq * 100, digits = 1), "%")),
    nudge_y = 3) +
  labs(x = "Flipper length (10mm classes)",
       y = "Absolute frequency",
       title = "Flipper lengths distribution",
       subtitle = "Percentages over the bars")
# dev.off()


    
    






